# Generated by Django 4.1.5 on 2023-01-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supmart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='predicted',
            field=models.FloatField(default=0),
        ),
    ]
